#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=16GB
#SBATCH --partition=gpu
#SBATCH --gres=gpu:p100:1
#SBATCH --time=1:00:00

conda activate metahate
module load conda

cd "/scratch1/hnghiem/Meta_Learning_Hatespeech/Code/scripts"
source activate metahate

declare -a arr=("trac" "davidson")

for h in "${arr[@]}"; do \
        python run_test.py --config_key MAML_test --holdout_set $h
done;

conda deactivate

