#!/bin/bash

#SBATCH --nodes=1
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=8
#SBATCH --mem=16GB
#SBATCH --partition=gpu
#SBATCH --gres=gpu:p100:1
#SBATCH --time=10:00:00


module load conda

cd "/scratch1/hnghiem/Meta_Learning_Hatespeech/Code/scripts"
source activate metahate

declare -a arr=("trac" "davidson")

for h in "${arr[@]}"; do \
        python run_binary.py  --config_key binary_basic --holdout_set $h
done;

rm -rf runs
rm -rf "'"
conda deactivate

